auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Randy's Blog
url: http://www.randyho.com
feed: /atom.xml
author_info: <a href="http://www.randyho.com/">Randy</a>
